### ISSUE TITLE
How to format into HH:MM:SS?

### ISSUE THREAD

**Issue by jrmallorca** [AndresR173/countdown_progress_indicator#5]
Hello,
I was just wondering if there was a way to format the time indicator text like HH:MM:SS?

I've also noticed that multiple calls to pause() and resume() will slow down the timer. Is there a fix for that?

**Comment by AndresR173** [comment]
Hi @jrmallorca, The widget doesn't support formats, but that's a nice feature. I'll work on that for the next release.

Regarding the timer, I haven't seen any issues, but thanks for notifying me. I'll take a look

**Comment by morio77** [comment]
@jrmallorca 

>I've also noticed that multiple calls to pause() and resume() will slow down the timer. Is there a fix for that?

"resume()” has been fixed. https://github.com/AndresR173/countdown_progress_indicator/pull/6  
Please import 0.1.1

**Comment by Haquoctien** [comment]
Hi, I saw this just after making the PR for this exact feature. Please take a look @AndresR173.
https://github.com/AndresR173/countdown_progress_indicator/pull/7

**Comment by AndresR173** [comment]
> Hi, I saw this just after making the PR for this exact feature. Please take a look @AndresR173. #7

Thank you so much, I updated the lib based on your PR, pls take a look at version 0.1.2
